"""verificar que sea email valido y sea unico

Revision ID: 3108e4cca3a8
Revises: 7672ec9f0601
Create Date: 2024-12-11 14:18:44.158238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3108e4cca3a8'
down_revision: Union[str, None] = '7672ec9f0601'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'customer', ['email'])
    op.drop_column('customer', 'username')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'customer', type_='unique')
    # ### end Alembic commands ###
